name: Build Fat JAR and Deploy to Heroku

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the fat JAR using custom task
      - name: Build Fat JAR
        run: ./gradlew buildFatJar

      # Step 5: Upload the fat JAR as an artifact
      - name: Upload fat JAR
        uses: actions/upload-artifact@v3
        with:
          name: fat-jar
          path: server/build/libs/server-all.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 1: Download Fat JAR Artifact
      - name: Download Fat JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: fat-jar
          path: ./server/build/libs  # Make sure this matches the artifact upload path

      # Step 2: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Step 3: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
          # Assuming you have a Procfile with the correct `web` command for Heroku
          heroku deploy:jar ./server/build/libs/server-all.jar --app your-app-name
